stages:
  - verify
  - package

verify-x64:
  stage: verify
  tags:
    - x64

  script:
    - touch vendor
    - make clean
    - go mod tidy
    - go fmt ./...; [[ -z $(git status -s --ignore-submodule) ]] || exit -1
    - make
    - make test

package-x64:
  stage: package
  tags:
    - x64

  script:
    - rpmbuild -bb droplet.spec -D '_rpmdir .' --buildroot $(pwd)/.rpmbuild
  artifacts:
    paths:
    - x86_64/droplet*.rpm
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/


docker-multi-platform:
  stage: package
  tags:
    - docker
  variables:
    VERSION: "echo $${CI_COMMIT_REF_NAME//B_LC_RELEASE_} | tr '_' '.' | sed 's/master/latest/'"
    RELEASE: "/usr/bin/git rev-list --count HEAD"
  script:
    - ~/build-deepflow droplet $(eval $VERSION)  $(pwd) 
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/

docker-x64:
  stage: package
  tags:
    - x64
  variables:
    VERSION: "echo $${CI_COMMIT_REF_NAME//B_LC_RELEASE_} | tr '_' '.' | sed 's/master/latest/'"
    RELEASE: "/usr/bin/git rev-list --count HEAD"
  script:
    - docker build -t docker-hosted.nexus.yunshan.net/droplet:$(eval $VERSION) ./
    - docker build -t docker-hosted.nexus.yunshan.net/droplet:$(eval $VERSION).$(eval $RELEASE) ./
    - docker push docker-hosted.nexus.yunshan.net/droplet:$(eval $VERSION)
    - docker push docker-hosted.nexus.yunshan.net/droplet:$(eval $VERSION).$(eval $RELEASE)
    - docker rmi docker-hosted.nexus.yunshan.net/droplet:$(eval $VERSION) || true
    - docker rmi docker-hosted.nexus.yunshan.net/droplet:$(eval $VERSION).$(eval $RELEASE) || true
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/

verify-arm64:
  stage: verify
  tags:
    - ecs-arm64

  script:
    - touch vendor
    - make clean
    - go mod tidy
    - go fmt ./...; [[ -z $(git status -s --ignore-submodule) ]] || exit -1
    - make

package-arm64:
  stage: package
  tags:
    - ecs-arm64

  script:
    - rpmbuild -bb droplet_arm64.spec -D '_rpmdir .' --buildroot $(pwd)/.rpmbuild
  artifacts:
    paths:
    - aarch64/droplet*.rpm
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/
