stages:
  - verify
  - package

verify-x64:
  stage: verify
  tags:
    - x64

  script:
    - go mod tidy
    - go fmt ./...; [[ -z $(git status -s --ignore-submodule) ]] || exit -1
    - make
    - make test

package-x64:
  stage: package
  tags:
    - x64

  script:
    - rpmbuild -bb droplet.spec -D '_rpmdir .' --buildroot $(pwd)/.rpmbuild
  artifacts:
    paths:
    - x86_64/droplet*.rpm
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/

docker-x64:
  stage: package
  tags:
    - x64
  script:
    - make droplet
    - docker build --add-host nexus.x.lan:10.30.2.201 -t droplet:$CI_COMMIT_REF_NAME ./
    - docker tag droplet:$CI_COMMIT_REF_NAME nexus.x.lan:5000/droplet:$CI_COMMIT_REF_NAME
    - docker push nexus.x.lan:5000/droplet:$CI_COMMIT_REF_NAME
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/

verify-arm64:
  stage: verify
  tags:
    - arm64

  script:
    - go mod tidy
    - go fmt ./...; [[ -z $(git status -s --ignore-submodule) ]] || exit -1
    - make

package-arm64:
  stage: package
  tags:
    - arm64

  script:
    - rpmbuild -bb droplet.spec -D '_rpmdir .' --buildroot $(pwd)/.rpmbuild
  artifacts:
    paths:
    - aarch64/droplet*.rpm
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/

