stages:
  - verify
  - package

verify-x64:
  stage: verify
  tags:
    - x64

  script:
    - go mod tidy
    - go fmt ./...; [[ -z $(git status -s --ignore-submodule) ]] || exit -1
    - make
    - make test

package64:
  stage: package
  tags:
    - x64

  script: rpmbuild -bb droplet.spec -D '_rpmdir .' --buildroot $(pwd)/.rpmbuild
  artifacts:
    paths:
    - x86_64/droplet*.rpm
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/

verify-arm64:
  stage: verify
  tags:
    - arm64

  script:
    - go mod tidy
    - go fmt ./...; [[ -z $(git status -s --ignore-submodule) ]] || exit -1
    - make

packagearm64:
  stage: package
  tags:
    - arm64

  script: rpmbuild -bb droplet.spec -D '_rpmdir .' --buildroot $(pwd)/.rpmbuild
  artifacts:
    paths:
    - aarch64/droplet*.rpm
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/
