stages:
  - verify
  - package

verify:
  stage: verify
  script:
    - go mod tidy
    - go fmt ./...; [[ -z $(git status -s --ignore-submodule) ]] || exit -1
    - make
    - make test

package:
  stage: package
  script: rpmbuild -bb droplet.spec -D '_rpmdir .' --buildroot $(pwd)/.rpmbuild
  artifacts:
    paths:
    - x86_64/droplet*.rpm
    - x86_64/pcap-rest-*.rpm
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/
