stages:
  - verify
  - package

verify-x64:
  stage: verify
  tags:
    - x64

  script:
    - touch vendor
    - make clean
    - go mod tidy
    - go fmt ./...; [[ -z $(git status -s --ignore-submodule) ]] || exit -1
    - make
    - make test

package-x64:
  stage: package
  tags:
    - x64

  script:
    - rpmbuild -bb droplet.spec -D '_rpmdir .' --buildroot $(pwd)/.rpmbuild
  artifacts:
    paths:
    - x86_64/droplet*.rpm
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/

docker-x64:
  stage: package
  tags:
    - x64
  script:
    - make
    - docker rmi nexus.yunshan.net:5000/droplet:$(echo ${CI_COMMIT_REF_NAME//B_LC_RELEASE_} | tr '_' '.' | sed 's/master/latest/') || true
    - docker build -t nexus.yunshan.net:5000/droplet:$(echo ${CI_COMMIT_REF_NAME//B_LC_RELEASE_} | tr '_' '.' | sed 's/master/latest/') ./
    - docker push nexus.yunshan.net:5000/droplet:$(echo ${CI_COMMIT_REF_NAME//B_LC_RELEASE_} | tr '_' '.' | sed 's/master/latest/')
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/

verify-arm64:
  stage: verify
  tags:
    - arm64

  script:
    - touch vendor
    - make clean
    - go mod tidy
    - go fmt ./...; [[ -z $(git status -s --ignore-submodule) ]] || exit -1
    - make

package-arm64:
  stage: package
  tags:
    - arm64

  script:
    - rpmbuild -bb droplet.spec -D '_rpmdir .' --buildroot $(pwd)/.rpmbuild
  artifacts:
    paths:
    - aarch64/droplet*.rpm
  only:
    - master
    - /B_LC_RELEASE_.*/
    - /feature-.*/
