controller-ips:
  - 127.0.0.1
# controller listen port
controller-port: 20035
# logfile path
log-file: /var/log/droplet/droplet.log
# loglevel: "debug/info/warn/error"
log-level: info
# remote statsd server
statsd-server: 127.0.0.1
# profiler
profiler: false
# public traffic
data-interfaces: []
# mirrored traffic
tap-interfaces: []
# zeroes
zeroes:
- ip: 172.16.1.152
  port: 20202
- ip: 172.16.1.153
  port: 20202
stream:
  ip: 172.16.1.153
  port: 20201
# flow timeout
flow-timeout:
  # inerval time for long flow, in seconds
  force-report-interval: 60
  # time for an established tcp flow, in seconds
  established: 300
  # timeout for tcp closing stage and get rst after established, in seconds
  closing-rst: 35
  # timeout for opening stage, flow with exception and single direction, in seconds
  others: 5
# packet and flow queue size
queue-size: 65536
# adapter write queue count
adapter-queue-count: 2
# flow generator read queue count
flow-queue-count: 2
# concurrent flow count limit
flow-count-limit: 1048576
# size of policy fast-path map, and
# labeler-queue-count*1024 <= policy-map-size <= labeler-queue-count*1048576
policy-map-size: 1048576
