controller-ips:
  - 127.0.0.1
# controller listen port
controller-port: 20035
# logfile path
log-file: /var/log/droplet/droplet.log
# loglevel: "debug/info/warn/error"
log-level: info
# remote statsd server
statsd-server: 127.0.0.1
# profiler
profiler: false
# public traffic
data-interfaces: []
# mirrored traffic
tap-interfaces: []
# zeroes
zeroes:
- ip: 172.16.1.152
  port: 20202
- ip: 172.16.1.153
  port: 20202
stream:
  ip: 172.16.1.153
  port: 20201
