controller-ips:
  - 127.0.0.1
# controller listening port
controller-port: 20035
# Rpc synchronization timeout default 8s
rpc-timeout: 8
# logfile path
log-file: /var/log/droplet/droplet.log
# loglevel: "debug/info/warn/error"
log-level: info
# profiler
profiler: false
# maximum usage of cpu cores, 0 means no limit
max-cpus: 0
adapter:
  # udp socket buffer size (Bytes) for receiving trident traffic,
  # default 32MB, and maximum 2GB
  # note that the actual value will depend on the minimum between
  # socket-buffer-size and the socket config via sysctl
  socket-buffer-size: 33554432
  # cache size (#) for resuming the order of received trident traffic,
  # default value is 64,
  # 64 <= value <= 1024, value is 1024 when value > 1024
  ordering-cache-size: 64
# internal queues conf
queue:
  # ----------- 并行度 -----------
  # 传输网包的队列数量，也是网包处理（以网包作为输入）模块的并行度，默认为1，最大16
  packet-queue-count: 1
  # 传输网包的每个队列的长度，默认为65536
  packet-queue-size: 65536
labeler:
  # whether to use first-path processing only
  fast-path-disable: false
  # size of policy fast-path map, and
  # map-size-limit >= filter-queue-count*1024
  # map-size-limit <= filter-queue-count*1048576
  map-size-limit: 1048576
pcap:
  # 计算TCP/IP checksum，默认不计算
  tcpip-checksum: false
  # 单次写入文件的块大小，默认64KB
  block-size-kb: 64
  # 同时在写的最大pcap文件数，默认5000
  max-concurrent-files: 5000
  # 每个pcap文件的最大大小，默认25MB，但是1秒内即使超过该值也不会切分文件
  max-file-size-mb: 25
  # 所有pcap文件的最大总大小，默认100GB
  max-directory-size-gb: 100
  # 磁盘剩余空间不足该数值时进行删除，默认10GB
  disk-free-space-margin-gb: 10
  # 每个pcap文件的最大时间，默认300秒
  max-file-period-second: 300
  # 每个pcap文件的保留时间，默认7天
  max-file-keep-day: 7
  # pcap文件存储的文件夹
  file-directory: /var/lib/droplet/pcap
