controller-ips:
  - 127.0.0.1
# controller listening port
controller-port: 20035
# logfile path
log-file: /var/log/droplet/droplet.log
# loglevel: "debug/info/warn/error"
log-level: info
# profiler
profiler: false
# interfaces for mirrored traffic from ISP or TOR
tap-interfaces: []
# conf for connection with outside stream
stream: 127.0.0.1
stream-port: 20201
# conf for connection with outside zeroes
zero-hosts: []
#  - 127.0.0.1
zero-port: 20202
# internal queues conf
queue:
  # packet and flow queue size
  queue-size: 65536
  # labeler read queue count
  labeler-queue-count: 8
  # flow generator read queue count
  flow-generator-queue-count: 2
  # metering app read queue count
  metering-app-queue-count: 8
  # flow app read queue count
  flow-app-queue-count: 2
# internal labeler conf
labeler:
  # size of policy fast-path map, and
  # map-size-limit >= filter-queue-count*1024
  # map-size-limit <= filter-queue-count*1048576
  map-size-limit: 1048576
# internal flow generator conf
flow-generator:
  # concurrent flow count limit
  flow-count-limit: 1048576
  # hard output interval for long flow, in seconds
  force-report-interval: 60
  # idle timeout for established tcp flow, in seconds
  established-timeout: 300
  # idle timeout for closing tcp flow,
  # or tcp flow with rst after established,
  # or non-tcp flow with dual direction, in seconds
  closing-rst-timeout: 35
  # idle timeout for opening tcp flow,
  # or tcp flow with exception,
  # or flow with single direction, in seconds
  others-timeout: 5
#geo-file-location: /opt/droplet/ip_info_mini.json
