controller-ips:
  - 127.0.0.1
# controller listen port
controller-port: 20035
# logfile path
log-file: /var/log/droplet/droplet.log
# loglevel: "debug/info/warn/error"
log-level: info
# profiler
profiler: false
# DANGEROUS: possible flood when close
close-flood-check: false
# public traffic
data-interfaces: []
# mirrored traffic
tap-interfaces: []
